version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ checksum ".circle-sha" }}
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
          - v1-repo-{{ checksum ".circle-sha" }}
      - run: npm run semantic-release || true

workflows:
  version: 2
  deploy:
    jobs:
      - install
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: master
